using System.Reflection;
using RememberAll.src.DTOs;
using RememberAll.src.DTOs.Create;
using RememberAll.src.Entities;

namespace RememberAll.src.Extensions;

public static class EntityDtoMappingExtensions
{

    #region User Mappings
    public static User ToEntity(this CreateUserDto createUserDto)
    {
        return new()
        {
            Name = createUserDto.Name,
            Email = createUserDto.Email,
        };
    }

    public static User ToEntity(this UserDto userDto)
    {
        return new()
        {
            Id = userDto.Id,
            Name = userDto.Name!,
            Email = userDto.Email!,
        };
    }

    public static UserDto ToDto(this User user)
    {
        return new(
            Id: user.Id,
            Name: user.Name,
            Email: user.Email
        );
    }
    #endregion

    #region TodoList Mappings
    public static TodoList ToEntity(this CreateTodoListDto createTodoListDto, User owner)
    {
        return new()
        {
            OwnerId = owner.Id,
            Name = createTodoListDto.Name,
        };
    }

    public static TodoListDto ToDto(this TodoList todoList)
    {
        return new(
            Id: todoList.Id,
            OwnerId: todoList.OwnerId,
            Name: todoList.Name,
            UpdatedAt: todoList.UpdatedAt,
            Items: todoList.Items.Select(item => item.ToDto()).ToList()
        );
    }

    public static ICollection<TodoListDto> ToDtos(this ICollection<TodoList> todoLists) =>
        todoLists.Select(list => list.ToDto()).ToList();
    #endregion

    #region TodoItem Mappings
    public static TodoItem Entity(this CreateTodoItemDto createTodoItemDto, TodoList todoList)
    {
        return new()
        {
            TodoListId = todoList.Id,
            Text = createTodoItemDto.Text
        };
    }
    public static TodoItem ToEntity(this CreateTodoItemDto createTodoItemDto, TodoList todoList)
    {
        return new()
        {
            TodoListId = createTodoItemDto.TodoListId,
            Text = createTodoItemDto.Text
        };
    }

    public static TodoItemDto ToDto(this TodoItem todoItem)
    {
        return new(
            Id: todoItem.Id,
            Text: todoItem.Text,
            IsCompleted: todoItem.IsCompleted,
            CompletionCount: todoItem.CompletionCount
        );
    }

    public static ICollection<TodoItemDto> ToDtos(this ICollection<TodoItem> todoItems) =>
        todoItems.Select(item => item.ToDto()).ToList();
    #endregion

    #region ListAccess Mappings
    public static ListAccess ToEntity(this CreateListAccessDto createListAccessDto, User user, TodoList list)
    {
        return new()
        {
            UserId = createListAccessDto.UserId,
            ListId = createListAccessDto.ListId,
        };
    }

    public static ListAccess ToEntity(this ListAccessDto listAccessDto, User user, TodoList list)
    {
        return new()
        {
            Id = listAccessDto.Id,
            UserId = listAccessDto.UserId,
            ListId = listAccessDto.ListId,
        };
    }

    public static ListAccessDto ToDto(this ListAccess listAccess)
    {
        return new(
            Id: listAccess.Id,
            UserId: listAccess.UserId,
            UserName: listAccess.User!.Name,
            ListId: listAccess.ListId,
            ListName: listAccess.List!.Name
        );
    }

    public static ICollection<ListAccessDto> ToDtos(this ICollection<ListAccess> listAccesss) =>
        listAccesss.Select(la => la.ToDto()).ToList();
    #endregion

    #region Invite Mappings
    public static Invite ToEntity(this CreateInviteDto createInviteDto, Guid inviteSenderId, Guid InviteReceiverId)
    {
        return new()
        {
            InviteSenderId = inviteSenderId,
            InviteRecieverId = InviteReceiverId,
            ListId = createInviteDto.ListId,
        };
    }

    public static InviteDto ToDto(this Invite invite)
    {
        return new(
            Id: invite.Id,
            InviteSenderId: invite.InviteSenderId,
            InviteSenderName: invite.InviteSender?.Name,
            InviteRecieverId: invite.InviteRecieverId,
            InviteRecieverName: invite.InviteReciever?.Name,
            ListId: invite.ListId,
            ListName: invite.List!.Name
        );
    }

    public static ListAccess ToListAccess(this Invite invite)
    {
        return new()
        {
            UserId = invite.InviteRecieverId,
            ListId = invite.ListId,
        };
    }

    public static ICollection<InviteDto> ToDtos(this ICollection<Invite> invites) =>
        invites.Select(invite => invite.ToDto()).ToList();
    #endregion

    // update Entity field only if DTO field is not null
    // THIS WAS GENERATED BY AI
    public static TEntity ApplyNonNullValuesFromDto<TEntity, TDto>(this TEntity entity, TDto dto)
        where TEntity : BaseEntity
    {
        var entityProperties = typeof(TEntity).GetProperties(BindingFlags.Public | BindingFlags.Instance)
            .Where(p => p.CanWrite && p.Name != nameof(BaseEntity.Id));

        var dtoProperties = typeof(TDto).GetProperties(BindingFlags.Public | BindingFlags.Instance)
            .ToDictionary(p => p.Name, p => p);

        foreach (var entityProp in entityProperties)
        {
            if (dtoProperties.TryGetValue(entityProp.Name, out var dtoProp))
            {
                var dtoValue = dtoProp.GetValue(dto);
                if (dtoValue is not null)
                {
                    // Handle nullable<T> to T conversion (e.g., float? -> float)
                    var targetType = Nullable.GetUnderlyingType(entityProp.PropertyType) ?? entityProp.PropertyType;
                    var convertedValue = Convert.ChangeType(dtoValue, targetType);
                    entityProp.SetValue(entity, convertedValue);
                }
            }
        }

        return entity;
    }

}