// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RememberAll.src.Data;

#nullable disable

namespace RememberAll.src.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260131211522_AuthImplementation")]
    partial class AuthImplementation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.1");

            modelBuilder.Entity("RememberAll.src.Entities.Invite", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("InviteRecieverId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("InviteSenderId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ListId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("InviteSenderId");

                    b.HasIndex("ListId");

                    b.HasIndex("InviteRecieverId", "ListId")
                        .IsUnique();

                    b.ToTable("Invites");
                });

            modelBuilder.Entity("RememberAll.src.Entities.ListAccess", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ListId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("ListId", "UserId")
                        .IsUnique();

                    b.ToTable("ListAccess");
                });

            modelBuilder.Entity("RememberAll.src.Entities.TodoItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("CompletionCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TodoListId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TodoListId");

                    b.ToTable("TodoItems");
                });

            modelBuilder.Entity("RememberAll.src.Entities.TodoList", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("TodoLists");
                });

            modelBuilder.Entity("RememberAll.src.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("RememberAll.src.Entities.Invite", b =>
                {
                    b.HasOne("RememberAll.src.Entities.User", "InviteReciever")
                        .WithMany("InvitesReceived")
                        .HasForeignKey("InviteRecieverId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RememberAll.src.Entities.User", "InviteSender")
                        .WithMany("InvitesSent")
                        .HasForeignKey("InviteSenderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RememberAll.src.Entities.TodoList", "List")
                        .WithMany("Invites")
                        .HasForeignKey("ListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InviteReciever");

                    b.Navigation("InviteSender");

                    b.Navigation("List");
                });

            modelBuilder.Entity("RememberAll.src.Entities.ListAccess", b =>
                {
                    b.HasOne("RememberAll.src.Entities.TodoList", "List")
                        .WithMany("Accessors")
                        .HasForeignKey("ListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RememberAll.src.Entities.User", "User")
                        .WithMany("ListAccess")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("List");

                    b.Navigation("User");
                });

            modelBuilder.Entity("RememberAll.src.Entities.TodoItem", b =>
                {
                    b.HasOne("RememberAll.src.Entities.TodoList", "TodoList")
                        .WithMany("Items")
                        .HasForeignKey("TodoListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TodoList");
                });

            modelBuilder.Entity("RememberAll.src.Entities.TodoList", b =>
                {
                    b.HasOne("RememberAll.src.Entities.User", "Owner")
                        .WithMany("Lists")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("RememberAll.src.Entities.TodoList", b =>
                {
                    b.Navigation("Accessors");

                    b.Navigation("Invites");

                    b.Navigation("Items");
                });

            modelBuilder.Entity("RememberAll.src.Entities.User", b =>
                {
                    b.Navigation("InvitesReceived");

                    b.Navigation("InvitesSent");

                    b.Navigation("ListAccess");

                    b.Navigation("Lists");
                });
#pragma warning restore 612, 618
        }
    }
}
