using Microsoft.AspNetCore.Mvc;
using RememberAll.src.Exceptions;
using RememberAll.src.Exceptions.Interfaces;

namespace RememberAll.src.Middleware;

// THIS WAS GENERATED BY AI
public class GlobalExceptionMiddleware(RequestDelegate next, ILogger<GlobalExceptionMiddleware> logger)
{
    public async Task InvokeAsync(HttpContext context)
    {
        try
        {
            await next(context);
        }
        catch (Exception ex)
        {
            await HandleExceptionAsync(context, ex);
        }
    }

    private async Task HandleExceptionAsync(HttpContext context, Exception ex)
    {
        var statusCode = ex switch
        {
            ICustomHttpException httpEx => httpEx.StatusCode,
            _ => 500
        };

        if (statusCode >= 500)
            logger.LogError(ex, "Server error: {Message}", ex.Message);
        else
        {
            if (ex is AuthException authEx)
                logger.LogWarning("Client error: {Message}", authEx.InternalMessage);
            else
                logger.LogWarning(ex, "Client error: {Message}", ex.Message);
        }

        var problemDetails = new ProblemDetails
        {
            Status = statusCode,
            Title = GetTitle(statusCode),
            Detail = ex.Message,
            Instance = context.Request.Path
        };

        context.Response.StatusCode = statusCode;
        context.Response.ContentType = "application/problem+json";
        await context.Response.WriteAsJsonAsync(problemDetails);
    }

    private static string GetTitle(int statusCode) => statusCode switch
    {
        400 => "Bad Request",
        401 => "Unauthorized",
        403 => "Forbidden",
        404 => "Not Found",
        409 => "Conflict",
        500 => "Internal Server Error",
        _ => "Error"
    };
}