using System.Reflection;
using RememberAll.src.DTOs;
using RememberAll.src.Entities;

namespace RememberAll.src.Extensions;

public static class EntityDtoMappingExtensions
{

    #region User Mappings
    public static User ToEntity(this CreateUserDto createUserDto)
    {
        return new()
        {
            Name = createUserDto.Name!,
            Email = createUserDto.Email!,
        };
    }

    public static User ToEntity(this UserDto userDto)
    {
        return new()
        {
            Id = userDto.Id,
            Name = userDto.Name!,
            Email = userDto.Email!,
        };
    }

    public static UserDto ToDto(this User user)
    {
        return new(
            Id: user.Id,
            Name: user.Name,
            Email: user.Email
        );
    }

    #endregion

    // update Entity field only if DTO field is not null
    // THIS WAS GENERATED BY AI
    public static TEntity ApplyNonNullValues<TEntity, TDto>(this TEntity entity, TDto dto)
        where TEntity : BaseEntity
    {
        var entityProperties = typeof(TEntity).GetProperties(BindingFlags.Public | BindingFlags.Instance)
            .Where(p => p.CanWrite && p.Name != nameof(BaseEntity.Id));

        var dtoProperties = typeof(TDto).GetProperties(BindingFlags.Public | BindingFlags.Instance)
            .ToDictionary(p => p.Name, p => p);

        foreach (var entityProp in entityProperties)
        {
            if (dtoProperties.TryGetValue(entityProp.Name, out var dtoProp))
            {
                var dtoValue = dtoProp.GetValue(dto);
                if (dtoValue is not null)
                {
                    // Handle nullable<T> to T conversion (e.g., float? -> float)
                    var targetType = Nullable.GetUnderlyingType(entityProp.PropertyType) ?? entityProp.PropertyType;
                    var convertedValue = Convert.ChangeType(dtoValue, targetType);
                    entityProp.SetValue(entity, convertedValue);
                }
            }
        }

        return entity;
    }

}